# -*- coding: utf-8 -*-
"""kalukatorsederhana.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DwcZwQTRmAKytzPBuYbckO0hjU6wWQQz
"""

bil1 = int(input("Masukkan bilangan 1: "))
bil2 = int(input("Masukkan bilangan 2: "))
operator = input("Masukkan operator :")
if (operator == "+"):
  hasil = bil1 + bil2
  print ("hasil penjumlahan =", hasil)
elif (operator == "-"):
  hasil = bil1 - bil2
  print ("hasil pengurangan =", hasil)
elif (operator == "/"):
  hasil = bil1 / bil2
  print ("hasil pembagian =", hasil)
elif (operator == "*"):
  hasil = bil1 * bil2
  print ("hasil perkalian =", hasil)
elif (operator == "**"):
  hasil = bil1 ** bil2
  print ("hasil perpangkatan =", hasil)
else:
  print("maaf operator yang anda masukkan salah")